### ISSUE TITLE
Can't play video for some tv

### ISSUE THREAD

**Issue by LozariaVinok** [cybergarage/cybergarage-upnp#10]
Hi!
For some tv i can't play video. This happened because services sometimes include full path for SCPDURL, sontrolURL, eventSubURL and sometimes include path relative of description file path. 
Description file path: /dmr/ddd.xml

<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
<SCPDURL>/dmr/sdd_2.xml</SCPDURL>
<controlURL>/dmr/control_2</controlURL>
<eventSubURL>/dmr/event_2</eventSubURL>

Can you help me?
Log:
11-19 13:42:29.571: I/System.out(28780): CyberGarage warning : java.io.FileNotFoundException: /dmr/sdd_2.xml: open failed: ENOENT (No such file or directory)
11-19 13:42:29.571: I/System.out(28780): org.cybergarage.xml.ParserException: java.io.FileNotFoundException: /dmr/sdd_2.xml: open failed: ENOENT (No such file or directory)
11-19 13:42:29.571: I/System.out(28780):    at org.cybergarage.xml.Parser.parse(Parser.java:107)
11-19 13:42:29.571: I/System.out(28780):    at org.cybergarage.upnp.Service.getSCPDNode(Service.java:392)
11-19 13:42:29.576: I/System.out(28780):    at org.cybergarage.upnp.Service.getSCPDNode(Service.java:441)
11-19 13:42:29.576: I/System.out(28780):    at org.cybergarage.upnp.Service.getActionList(Service.java:471)
11-19 13:42:29.576: I/System.out(28780):    at org.cybergarage.upnp.Service.getAction(Service.java:490)

**Comment by wypx** [comment]
Service devService = dev.getService("urn:schemas-upnp-org:service:WANIPConnection:1");
								devService.setSCPDURL("http://192.168.31.1:5351/WANIPCn.xml");
								Action addPortAct = devService.getAction("AddPortMapping");

I using this way to solve it . but not best the path relative of description file path should be pasered in the library anyway.

**Comment by ximencx** [comment]
i have some question ， @wypx @cybergarage  video source is hls stream，how to solve it？

**Comment by jametang** [comment]
I have the same problem!
