### ISSUE TITLE
Crash for zero-length packets

### ISSUE THREAD

**Issue by Emill** [cybergarage/cybergarage-upnp#13]
{Cyber.SSDPNotifySocket/192.168.1.49:1900 -> 239.255.255.250:1900} {IllegalArgumentException} (@java.io.BufferedReader:<init>:109) java.lang.IllegalArgumentException: size <= 0 at 
java.io.BufferedReader.<init>(BufferedReader.java:109) at java.io.LineNumberReader.<init>(LineNumberReader.java:59)
at org.cybergarage.http.HTTPHeader.getValue(SourceFile:120)
at org.cybergarage.http.HTTPHeader.getValue(SourceFile:126)
at org.cybergarage.upnp.ssdp.SSDPPacket.getHost(SourceFile:138)
at org.cybergarage.upnp.ssdp.SSDPPacket.getHostInetAddress(SourceFile:193)
at org.cybergarage.upnp.ssdp.SSDPNotifySocket.run(SourceFile:134)
at java.lang.Thread.run(Thread.java:818)

**Comment by dlutfrank** [comment]
I have the same problem as you, did you fix this bug.

**Comment by gopalmudaliar** [comment]
I also got the same issue reported from the field.
