### ISSUE TITLE
Out of Memory!!!!

### ISSUE THREAD

**Issue by jametang** [cybergarage/cybergarage-upnp#22]
**Hello guys:
I have a problem when using cybergarage lib . The detail error log as follows:**
FATAL EXCEPTION: Cyber.HTTPServer//172.16.171.202:8058
08-14 11:12:37.647 15730  1550 E AndroidRuntime: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
08-14 11:12:37.647 15730  1550 E AndroidRuntime:        at java.lang.Thread.nativeCreate(Native Method)
08-14 11:12:37.647 15730  1550 E AndroidRuntime:        at java.lang.Thread.start(Thread.java:753)
08-14 11:12:37.647 15730  1550 E AndroidRuntime:        at org.cybergarage.http.HTTPServer.run(HTTPServer.java:243)
08-14 11:12:37.647 15730  1550 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)
08-14 11:12:37.651 15730  1548 E AndroidRuntime: FATAL EXCEPTION: Cyber.HTTPServer//fe80::3a37:8bff:feb4:7676%wlan0:8058

08-14 11:12:37.651 15730  1548 E AndroidRuntime: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
08-14 11:12:37.651 15730  1548 E AndroidRuntime:        at java.lang.Thread.nativeCreate(Native Method)
08-14 11:12:37.651 15730  1548 E AndroidRuntime:        at java.lang.Thread.start(Thread.java:753)
08-14 11:12:37.651 15730  1548 E AndroidRuntime:        at org.cybergarage.http.HTTPServer.run(HTTPServer.java:243)
08-14 11:12:37.651 15730  1548 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)

I guess that it is related to searching .However, I have no way to stop it .Anyone has good idea?

**Comment by aopi1125** [comment]
i had the same problem:
 java.lang.OutOfMemoryError
pthread_create (1040KB stack) failed: Out of memory
